language: cpp
sudo: true
before_install: wget --no-check-certificate https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
  && unzip -d packer packer_0.10.1_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer
script: packer version